# Generated by Django 3.2.9 on 2022-11-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='country',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='exprience',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='highestedu',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='jobcategory',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='jobdescription',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='max_salary',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='min_salary',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='website',
        ),
    ]
