# Generated by Django 3.2.9 on 2022-11-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221110_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='address',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='city',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='state',
        ),
    ]
