# Generated by Django 3.2.9 on 2022-11-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221110_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
