# Generated by Django 3.2.9 on 2022-11-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='max_salary',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='min_salary',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
